Testing Practice with Jest
eapenzacharias/TestingPractice pull request #2
Opened 2020-01-20 23:09 UTC by eapenzacharias

2020-01-22 15:17 UTC, mcrd25 requested changes
# Changes Required 🔍 👀 

Hi, @eapenzacharias and @serdg0, 👋 

You guys did a great job working together to get this project done. 😄 👏 
Your functions work well for the most part 🙂. There is only one function where you missed the mark slightly! 🙁 

### Required Changes
- Make the required changes to your `capitalize` function and update corresponding tests accordingly to expect the right result.

### Suggested Changes [OPTIONAL]
*These are changes you do not have to make*
- Address all changes marked by [OPTIONAL] to improve your code

***Please makes changes and submit another review request.
If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

2020-01-22 15:17 UTC, mcrd25 commented on capitalize/capitalize.js
> +const capitalize = string => string.slice(0, 1).toUpperCase() + string.slice(1).toLowerCase();
This method should only capitalize the first character of string now convert the rest to lower case.
Read carefully from this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/testing_practice/capitalize_requirement.png) from the [Odin Project](https://www.theodinproject.com/courses/javascript/lessons/testing-practice)

2020-01-22 15:17 UTC, mcrd25 commented on capitalize/capitalize.test.js
> +  expect(capitalize('TESTING')).toBe('Testing');
Because of your initial misunderstanding of the specifications of this function, your expectation is wrong.

2020-01-22 15:17 UTC, mcrd25 commented on capitalize/capitalize.test.js
> +  expect(capitalize('TeStInG')).toBe('Testing');
Same as above. Only the first Character should be capitalized

2020-01-22 15:17 UTC, mcrd25 commented on capitalize/capitalize.test.js
> +  expect(capitalize('TeStInG testinG')).toBe('Testing testing');
Same as previous

2020-01-22 15:17 UTC, mcrd25 commented on reverseString/reverseString.test.js
> +});
[OPTIONAL]
When you have a group of tests pertaining to one function/test case it is best to wrap them in a `describe` block.

```js
describe("reverseString", () => {
it('Reverse a single word', () => {
  expect(reverseString('Testing')).toBe('gnitseT');
});

it('Reverse a sentence', () => {
  expect(reverseString('Welcome to testing')).toBe('gnitset ot emocleW');
});

it('Reverse a word with multiple uppercase characters', () => {
  expect(reverseString('WariO')).toBe('OiraW');
}); 
}
```

2020-01-22 15:17 UTC, mcrd25 commented on calculator/calculator.test.js
> +
[OPTIONAL]
When you have a group of tests pertaining to one function/test case it is best to wrap them in a `describe` block.

```js
describe("calulator", () => {
it('adding two positive numbers', () => {
  expect(calculator.add(1, 2)).toBe(3);
});
// and so one ...
}
```

2020-01-22 15:17 UTC, mcrd25 commented on caesar/caesar.test.js
> +  expect(caesar('.[]{}?!', 2)).toBe('.[]{}?!');
[OPTIONAL]
When you have a group of tests pertaining to one function/test case it is best to wrap them in a `describe` block.

```js
describe("ceaser", () => {
// tests
it('wraps the alphabeth from a to z', () => {
  expect(caesar('azeroth', 1)).toBe('bafspui');
});
// more tests...
}
```

2020-01-22 15:17 UTC, mcrd25 commented on arrAnalysis/arrAnalysis.test.js
> +});
[OPTIONAL]
When you have a group of tests pertaining to one function/test case it is best to wrap them in a `describe` block.

```js
describe("analyze", () => {
it('return the values of an array', () => {
  expect(analyze([1, 8, 3, 4, 2, 6])).toStrictEqual({
    average: 4, min: 1, max: 8, length: 6,
  });
});

it('return the values of an array with a single integer', () => {
  expect(analyze([1])).toStrictEqual({
    average: 1, min: 1, max: 1, length: 1,
  });
});
}
```

2020-01-22 15:17 UTC, mcrd25 commented on calculator/calculator.test.js
> +  expect(calculator.add(1, 2)).toBe(3);
[OPTIONAL]
You can try leaving less human error in your test by avoiding the hardcoded values.
Like 3 could be `1 +2`
YOu could even have variables and variables that store larger numbers as well.
like `const num2 = 2` etc.
or 
`const bigNum = 123455678`

2020-01-22 15:43 UTC, serdg0 commented
For this code review, according to the last one, we:
- Fixed the capitalize method and tests 
- wrapped in blocks the tests.

2020-01-23 03:42 UTC, bellom approved these changes
## Hi Team :clap: 

**Great work making all the necessary corrections from the previous review.**

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit project completion form.
Good luck in the next milestone :slightly_smiling_face:_ 

Best,

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-01-23 17:40 UTC, merged